### ISSUE TITLE
TypeError: Interpreter.nativeGlobal.Number is not a function

### ISSUE THREAD

**Issue by shbobur** [mercmobily/JS-Interpreter#14]
I get this error when I run this code:
`moveForward(Number(10));`

This happens in my Node React app where I install the _Interpreter_ with **npm**.
But when I tested it by downloading and linking the interpreter manually everything works without any problems.
Is this a problem in my environment or something in npm module?

**Comment by marashiai** [comment]
@shbobur It's not easy to answer like this without having the bigger picture about where is `moveForward` defined, etc. If you could paste more context for the code that could help.
That being said this package is not an official package published by the js-interpreter maintainer, it's maintained by me because I also wanted to have the npm package. But it's basically a wrapper around the code directly cloned from the original source without changing anything extra so I would assume this should be identical to using the original js-interpreter code as long as they are pointing to the same commit hash.
I will have to update this to point to the latest hash, although I don't see any changes in the original repo that might be making difference in this behavior.

**Comment by marashiai** [comment]
I've updated the package with the most recent changes in the original repo, however, all those changes were documentation/demo file changes and won't have any behavioral impact.

**Comment by marashiai** [comment]
Well scratch that, I'm actually able to reproduce this on both npm and the original repo version. I'll reply in the issue you opened in the original repo: https://github.com/NeilFraser/JS-Interpreter/issues/214

**Comment by mercmobily** [comment]
@shbobur The NPM package is transitioning. I will have a look at this as soon as possible.
In the meantime, would you be able to see what the result is if you use https://www.npmjs.com/package/js-interpreter-npm ?

This is out of curiosity, and it is likely to have the same problem (or other problems). However, I would be curious to know if it does "just work".

Thanks.

**Comment by mercmobily** [comment]
@myuzio I forgot to mention, thank you for maintaining it during this time. I will try and make sure it will be possible to use it with CLI and maintain your existing code. I am assuming there are people out there who are counting on it to work.

**Comment by ako-deriv** [comment]
Anyone has any idea how to solve the problem?
I found a solution but it doesn't work as expected!

**Comment by mercmobily** [comment]
@ali-hosseini-fs we are in between switching things around. Things will be clearer soon. Have you tried following advice here?  https://github.com/mercmobily/JS-Interpreter/issues/14#issuecomment-898881949

**Comment by ako-deriv** [comment]
I checked it, seems it's working!
let me pass it to our qa team ;-)

**Comment by mercmobily** [comment]
Ok please!

**Comment by mercmobily** [comment]
Please do report back, I am very keen on knowing the outcome. The original
poster of this ticket seems to have disappeared.

Merc.

**Comment by ako-deriv** [comment]
It will take some days to test by our qa team! so far everything works fine.
I'm gonna revert after they did check it.

**Comment by ako-deriv** [comment]
one of the problems that I encountered in both of packages is this
 
![ksnip_20210905-124559](https://user-images.githubusercontent.com/81898967/132120300-7263f850-5e07-4da0-b079-a240ebe36e0e.png)

**Comment by mercmobily** [comment]
Hi,

I assume that's because of dependency.
I will make sure that is sorted out ASAP, whatever it takes.

Merc.

**Comment by ako-deriv** [comment]
it is related to latest npm version.

**Comment by mercmobily** [comment]
Hi,

Wait a sec... about the second problem:

> one of the problems that I encountered in both of packages is this

If you run 'npm install vm', do you still get the problem?

**Comment by ako-deriv** [comment]
No i just installed `vm-browserify` and applied it's suggested config on that error log and problem fixed.
 check [this out](https://github.com/ali-hosseini-fs/JS-Interpreter/blob/master/webpack.config.js)

**Comment by ako-deriv** [comment]
Also I deployed it to [npm](https://www.npmjs.com/package/@deriv/js-interpreter) as a temporary patch.
It's working but cli not works. so in my case we are not using it. 
I just added `self` instead of `this` in the [submodule repo](https://github.com/ako-org/JS-Interpreter/blob/self-used-instead-of-this/interpreter.js) (check line 180).
basically I forked both of repos and deploy it under our company's scope on the npm.

**Comment by mercmobily** [comment]
Hi,

OK.
We are trying to avoid the need to fork.
I will make sure things work out of the box ASAP.

Merc.

**Comment by ako-deriv** [comment]
I did those things just as a temporary solution.
By the way, Thanks
